name: Linux tests

on:
  push:         {branches: [master]}
  pull_request: {branches: [master]}

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - {imgtag: "python:2.7-buster",    crypto_ver: "2.6.1"}
          - {imgtag: "python:2.7-buster",    crypto_ver: "3.3.2"}
          - {imgtag: "python:3.5-buster",    crypto_ver: "2.6.1"}
          - {imgtag: "python:3.5-buster",    crypto_ver: "3.2.1"}
          - {imgtag: "python:3.6-bullseye",  crypto_ver: "2.6.1"}
          - {imgtag: "python:3.6-bullseye",  crypto_ver: "3.4.8"}
          - {imgtag: "python:3.7-bullseye",  crypto_ver: "2.6.1"}
          - {imgtag: "python:3.7-bullseye",  crypto_ver: "3.4.8"}
          - {imgtag: "python:3.8-bookworm",  crypto_ver: "2.6.1"}
          - {imgtag: "python:3.8-bookworm",  crypto_ver: "3.4.8"}
          - {imgtag: "python:3.9-bookworm",  crypto_ver: "2.9.2"}
          - {imgtag: "python:3.9-bookworm",  crypto_ver: "36.0.2"}
          - {imgtag: "python:3.10-bookworm", crypto_ver: "36.0.2"}
          - {imgtag: "python:3.10-bookworm", crypto_ver: "41.0.7"}
          - {imgtag: "python:3.11-bookworm", crypto_ver: "38.0.4"}
          - {imgtag: "python:3.11-bookworm", crypto_ver: "42.0.8"}
          - {imgtag: "python:3.12-bookworm", crypto_ver: "38.0.4"}
          - {imgtag: "python:3.12-bookworm", crypto_ver: "44.0.2"}
          - {imgtag: "python:3.13-bookworm", crypto_ver: "38.0.4"}
          - {imgtag: "python:3.13-bookworm", crypto_ver: "44.0.2"}

    container: "${{matrix.imgtag}}"
    steps:
      - uses: actions/checkout@v3

      - name: Python dependencies
        run: |
          pip install -r dev-requirements.txt
          pip install cryptography==${{matrix.crypto_ver}} PyNaCl
          if [ ${{matrix.imgtag}} = python:3.7-bullseye ]; then
            export DEBIAN_FRONTEND=noninteractive
            apt-get -q -y update
            apt-get -q -y install libkrb5-dev krb5-admin-server \
                            krb5-kdc krb5-user krb5-multidev openssh-server
            pip install gssapi==1.5.1 pyasn1==0.4.5 k5test==0.9.2
          fi
          pip install -e .
          pip freeze

      - name: Lint
        if: ${{ ! (contains(matrix.imgtag, ':2.7-') || contains(matrix.imgtag, ':3.5-')) }}
        run: |
          flake8 --version
          flake8 --show-source

      - name: Test
        run: |
          pytest -v

  docs:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r doc-requirements.txt
          pip install -e .
      - name: Build docs
        run: |
          sphinx-build -v -W sites/docs tmpbuild
