name: Linux tests

on:
  push:         {branches: [master]}
  pull_request: {branches: [master]}

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        imgtag:
          - "python:2.7-buster"
          - "python:3.4-stretch"
          - "python:3.5-buster"
          - "python:3.6-buster"
          - "python:3.7-buster"
          - "python:3.8-bullseye"
          - "python:3.9-bullseye"
          - "python:3.10-bullseye"
          - "pypy:2.7-7.3.5"
          - "pypy:3.7-7.3.5"
        crypto_ver:
          - "2.6"
        include:
          - {imgtag: "python:2.7-buster",   crypto_ver: "2.8"}
          - {imgtag: "python:3.7-buster",   crypto_ver: "2.8"}
          - {imgtag: "python:3.5-buster",   crypto_ver: "2.9.2"}
          - {imgtag: "python:3.9-bullseye", crypto_ver: "2.9.2"}
          - {imgtag: "python:2.7-buster",   crypto_ver: "3.1.1"}
          - {imgtag: "python:3.6-buster",   crypto_ver: "3.1.1"}
          - {imgtag: "python:3.7-buster",   crypto_ver: "3.4.7"}
          - {imgtag: "python:3.8-bullseye", crypto_ver: "3.4.7"}
          - {imgtag: "pypy:3.7-7.3.5",      crypto_ver: "3.4.7"}
          - {imgtag: "python:3.9-bullseye", crypto_ver: "36.0.0"}
          - {imgtag: "python:3.10-bullseye", crypto_ver: "36.0.0"}

    container: "${{matrix.imgtag}}"
    steps:
      - uses: actions/checkout@v2
      - name: System dependencies
        run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get -q -y update
            apt-get -q -y install libkrb5-dev krb5-admin-server \
                                     krb5-kdc krb5-user krb5-multidev \
                                     openssh-server locales
            # make non-ascii locale available for some tests
            echo "ru_RU.UTF-8 UTF-8" >>/etc/locale.gen
            echo "en_US.UTF-8 UTF-8" >>/etc/locale.gen
            locale-gen
      - name: Python dependencies
        run: |
          pip install -r dev-requirements.txt
          pip install cryptography==${{matrix.crypto_ver}} PyNaCl
          if [ ${{matrix.imgtag}} = python:2.7-buster ] || \
             [ ${{matrix.imgtag}} = python:3.6-buster ]; then
            pip install gssapi==1.5.1 pyasn1==0.4.5 k5test==0.9.2
          fi
          pip install -e .
          pip freeze
      - name: Lint
        run: |
          flake8 --version
          flake8 --show-source
      - name: Test
        run: |
          pytest -v

  docs:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r doc-requirements.txt
          pip install -e .
      - name: Build docs
        run: |
          sphinx-build -v -W sites/docs tmpbuild
